# Generated by Django 5.0.4 on 2024-04-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('total_number', models.IntegerField()),
                ('buy_now', models.IntegerField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=44)),
                ('marka', models.CharField(max_length=33)),
                ('model', models.CharField(max_length=33)),
                ('price', models.PositiveIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('mileage', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=44)),
                ('country', models.CharField(max_length=33)),
                ('with_photo', models.BooleanField()),
                ('color', models.CharField(max_length=33)),
                ('volume', models.FloatField()),
                ('description', models.TextField()),
            ],
        ),
    ]
