# Generated by Django 5.0.4 on 2024-04-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='number_en',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bet',
            name='number_ru',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bet',
            name='total_number_en',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bet',
            name='total_number_ru',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='city_en',
            field=models.CharField(max_length=44, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='city_ru',
            field=models.CharField(max_length=44, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='color_en',
            field=models.CharField(max_length=33, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='color_ru',
            field=models.CharField(max_length=33, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='country_en',
            field=models.CharField(max_length=33, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='country_ru',
            field=models.CharField(max_length=33, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='description_ru',
            field=models.TextField(null=True),
        ),
    ]
